M48
; DRILL file {KiCad 9.0.6} date 2026-08-01T14:39:10+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-01T14:39:10+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.386Y-40.552
X110.386Y-129.552
X224.386Y-40.552
X224.386Y-129.552
M30
